name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: "localhost"
      DB_PORT: "3306"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
      DB_NAME: "mydatabase"

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Start MySQL server
      run: |
        sudo apt update
        sudo apt install -y mysql-server
        sudo service mysql start
        sudo systemctl status mysql

  # Get temporary password
    - name: Get MySQL temp password
      run: |
        sudo grep 'temporary password' /var/log/mysql/error.log > /tmp/mysql_pass.txt
        export MYSQL_TEMP_PASSWORD=$(awk '{print $NF}' /tmp/mysql_pass.txt)
        echo "MySQL temporary password: $MYSQL_TEMP_PASSWORD"
    # Change root password
    - name: Change MySQL root password
      run: |
        sudo mysql -u root --password=$MYSQL_TEMP_PASSWORD -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';"
        sudo mysql -u root --password=1234 -e "CREATE DATABASE mydatabase;"
        sudo mysql -u root --password=1234 -e "CREATE USER 'myuser' IDENTIFIED BY 'mypassword';"
        sudo mysql -u root --password=1234 -e "GRANT ALL PRIVILEGES ON mydatabase.* TO 'myuser';"

    - name: Import SQL dumps
      run: |
        cd sql\ dumps
        mysqlimport --host=localhost --user=myuser --password=mypassword --database=mydatabase --ignore-lines=1 --fields-terminated-by=, --verbose ./file1.sql ./file2.sql

    - name: Install dependencies
      run: cd back && npm ci

    - name: Start server
      run: cd back && npm start &
      # Le symbole "&" permet d'exécuter la commande en arrière-plan

    - name: Run tests
      run: cd back && npm test