name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: "localhost"
      DB_PORT: "3306"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
      DB_NAME: "mydatabase"

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Start MySQL server
      run: |
        sudo apt update
        sudo apt install -y mysql-server
        sudo service mysql start
        sudo systemctl status mysql

    - name: Change MySQL root password
      run: |
        ls /var/log
        ls /var/log/mysql
        sudo cat /var/log/mysql/error.log

    - name: Import SQL dumps
      run: |
        cd sql\ dumps
        sudo mysql -p -h ${DB_HOST} -P ${DB_PORT} -u ${DB_USER} -p${DB_PASSWORD} ${DB_NAME} < file1.sql
        sudo mysql -p -h ${DB_HOST} -P ${DB_PORT} -u ${DB_USER} -p${DB_PASSWORD} ${DB_NAME} < file2.sql

    - name: Install dependencies
      run: cd back && npm ci

    - name: Start server
      run: cd back && npm start &
      # Le symbole "&" permet d'exécuter la commande en arrière-plan

    - name: Run tests
      run: cd back && npm test
